### ISSUE TITLE
Message: The api-version '2023-04-01-preview' is invalid. The supported versions are '2024-03-01,2023-07-01,2023-07-01-preview,2023-03-01-preview

### ISSUE THREAD

**Issue by Arwiin07** [microsoft/llmops-promptflow-template#121]
While running a pipeline,I am facing this issue

**Comment by mohanajuhi166** [comment]
@Arwiin07 that happens when we dont provide subscription_id, rg_name ,workspace_name and dont update llm_configs.json for named_entity_recognition, web_classification and math_coding. 
What I have done in this case, I created my fork https://github.com/mohanajuhi166/llmops-promptflow-template and followed steps here: https://github.com/microsoft/llmops-promptflow-template/blob/main/docs/github_workflows_how_to_setup.md  and updated my configs. 

You can view in my repository.

**Comment by mohanajuhi166** [comment]
this helped me run all the builds and pipeline successfully.
